name: 'AWS Lambda Deploy Function'
description: 'Deploy a Function to a Lambda through Github Actions'
author: 'zeagord'
branding:
  icon: 'cloud'
  color: 'green'
inputs:
  artifact:
    description: 'Jar or Zip package of the lambda'
    default: ''
  function-name:
    description: 'Name of the Lambda function'
    default: ''
  runtime:
    description: 'Runtime fo the Lambda, Java11 or Node11'
    default: ''
  handler:
    description: 'Name of the Handler'
    default: ''
  AWS_SECRET_KEY:
    description: 'AWS secret key'
    default: ''
  AWS_SECRET_ID:
    description: 'AWS secret key ID'
    default: ''
  AWS_REGION:
    description: 'AWS region'
    default: ''
outputs:
  time: # id of output
    description: 'Lambda is deployed'
runs:
  using: 'node12'
  main: 'index.js'